name: compile-pymeow
run-name: Automatic Build by @${{ github.actor }}
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fix Deps Error
        run: sudo apt-get install -y libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev libgl-dev libxxf86vm-dev
      - run: nimble install -y nimpy nimraylib_now x11 winim
      - run: nim c pyMeow
      - run: |
          ls **/*.pyd
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Automatic Build"
          automatic_release_tag: "latest"
          files: | 
            **/*.pyd
